/**
 * b3nd.rig.ts — generated by `bnd config init`
 *
 * This file is your rig definition. Every bnd command (send, receive,
 * read, observe, node) loads this module and uses the rig it exports.
 *
 * Edit freely — change targets, add multiple connections with patterns,
 * swap to a local store for `bnd node`, etc.
 */

import {
  connection,
  createClientFromUrl,
  Rig,
} from "jsr:@bandeira-tech/b3nd-core@^0.12.0/rig";

export default async () => {
  // Default: talk to a local node over HTTP.
  // Replace with your real node URL, or wire multiple targets with patterns.
  const client = await createClientFromUrl("http://localhost:3000");
  const all = connection(client, ["*"]);

  return new Rig({
    routes: {
      send: [all],
      receive: [all],
      read: [all],
      observe: [all],
    },
  });
};
