/**
 * b3nd.rig.ts — generated by `bnd config init`
 *
 * This file is your rig definition. Every bnd command (send, receive,
 * read, observe, node) loads this module and uses the rig it exports.
 *
 * Edit freely — change targets, add multiple connections with patterns,
 * swap to a local store for `bnd node`, etc.
 */

import { connection, Rig } from "jsr:@bandeira-tech/b3nd-core@^0.24.0/rig";
import { HttpClient } from "jsr:@bandeira-tech/b3nd-move@^0.19.0/http/client";

export default () => {
  // Default: talk to a local node over HTTP.
  // Replace with your real node URL, or wire multiple targets with patterns.
  // `**` matches any URI; tighten it (`mutable://**`, `myproto://app/**`) to
  // shard writes/reads across multiple connections.
  const client = new HttpClient({ url: "http://localhost:3000" });
  const all = connection(client, ["**"]);

  return new Rig({
    routes: {
      send: [all],
      receive: [all],
      read: [all],
      observe: [all],
    },
  });
};
